apiVersion: v2
name: tracking-system
description: A Helm chart for Kubernetes
type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: traefik
    version: "20.8.0"
    repository: "https://traefik.github.io/charts"
    condition: traefik.enabled

  - name: kube-prometheus-stack
    version: "56.6.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
