targets:
  - name: dev
    args:
      environment: dev
      namespace: dev
    context: gke_angular-vector-448122-q6_southamerica-east1-a_pfc-tracker-system

  - name: production
    args:
      environment: prod
      namespace: prod

    context: gke_angular-vector-448122-q6_southamerica-east1-a_pfc-tracker-system

#Defines variables that can be used in deployment files.
args:
  - name: environment
  - name: namespace

discriminator: kluctl-{{ target.name }}
