apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-tracking-system
  namespace: tracking-system-{{ .Values.namespace }}
  labels:
    app: front-tracking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-tracking-system
  template:
    metadata:
      labels:
        app: front-tracking-system
    spec:
      containers:
        - name: front-tracking-system
          image: southamerica-east1-docker.pkg.dev/angular-vector-448122-q6/pfc-tracking-system/nextjs-react-tracking-system-app:dev
          ports:
            - containerPort: 4000
              protocol: TCP
          resources:
            limits:
              memory: "963Mi"
            requests:
              memory: "128Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
