apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: front-tracking-system
  namespace: tracking-system-{{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`tracking-system.app`)
      services:
        - kind: Service
          name: front-tracking-system
          port: 4000
          scheme: http
