apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefixes-front
  namespace: tracking-system-{{ .Values.namespace }}
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /front/{{ .Values.environment }}
