apiVersion: v1
kind: Service
metadata:
  name: front-tracking-system
  namespace: tracking-system-{{ .Values.namespace }}
spec:
  selector:
    app: front-tracking-system
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
