apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-node
  namespace: tracking-system-{{ args.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`tracking-system.app`) && PathPrefix(`/api/node/{{ args.environment }}`)
      middlewares:
        - name: strip-api-prefixes
      services:
        - kind: Service
          name: api-node
          port: 3000
          scheme: http
