apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefixes
  namespace: tracking-system-{{ args.namespace }}
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /api/node/{{ args.environment }}
