apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: <NAME>
  namespace: external-secrets
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store # name of the SecretStore (or kind specified)
  target:
    name: <NAME OF THE K8s> # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: <KEY> # key in the Kubernetes Secret
      remoteRef:
        key: <SECRET KEY> # name of the GCPSM secret key
