apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
  namespace: tracking-system-{{ .Values.namespace }}
  labels:
    app: api-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-node
  template:
    metadata:
      labels:
        app: api-node
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api-node
          image: southamerica-east1-docker.pkg.dev/angular-vector-448122-q6/pfc-tracking-system/serverless-nest-ts-aws-monolith:{{ .Values.image.tag }}
          env:
            - name: API_PORT
              value: "3000"
          envFrom:
            - secretRef:
                name: api-node-secrets
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "2000Mi"
              cpu: "1500m"
            limits:
              memory: "2000Mi"
              cpu: "2000m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
